server:
  port: 10000
spring:
  profiles:
    active: prod
  application:
    name: gulimall-product
  cloud:
    nacos:
      discovery:
        server-addr: http://122.112.200.54:8848
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.xml

