server:
  port: 88
spring:
  application:
    name: gulimall_gateway
  cloud:
    nacos:
      discovery:
        server-addr: 122.112.200.54:8848
    gateway:
      routes:
        - id: test_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
debug: true
